### ISSUE TITLE
missing buttons in top bar

### ISSUE THREAD

**Issue by hannesdelbeke** [leixingyu/unrealScriptEditor#3]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3758308/232478189-53a641d5-541d-43fa-9f27-c5e6299a6442.png">

The buttons are there, but appear as if they are not. because they don't show the images.
This is likely an issue with the stylesheet hookup, or a icon-resource not found issue.

```python
MODULE_PATH = os.path.dirname(os.path.abspath(__file__))
MODULE_NAME = os.path.basename(MODULE_PATH)
UI_PATH = os.path.join(MODULE_PATH, 'ui', 'script_editor.ui')
CONFIG_PATH = os.path.join(MODULE_PATH, 'config.txt')
```
I printed MODULE_PATH, which appears correct. 
so that means this should be correct too: 
`QtCore.QResource.registerResource(os.path.join(MODULE_PATH, "icons", "icons.rcc"))`

**Comment by leixingyu** [comment]
Thanks for flagging, I'll check it out

**Comment by leixingyu** [comment]
I just did a fresh install and the icons appeared fine on my end, but I guess it's safer (and less hassle) to not compile those into resources since there are only a few.

**Comment by leixingyu** [comment]
alrighty, fix is up.

**Comment by hannesdelbeke** [comment]
I'm afraid the buttons are still invisible with the latest update.
I tested this with PySide2

**Comment by hannesdelbeke** [comment]
- if i set the path to an absolute path in `script_editor.ui` it works
- if i change the relative path from `../icons/clearAll.png` to `../unrealscripteditor-plugin/pythonscripteditor/content/python/unrealscripteditor/icons/clearAll.png` it also works

it seems the relativeness is not from the ui file, but from something else. not sure what exactly
![image](https://github.com/leixingyu/unrealScriptEditor/assets/3758308/ebb4f3a6-c80f-4597-8476-11e190b84f28)

This makes me think that either it's related to how the environment is setup for the project.

Or there's a bug in the Qt module.
The UI loads correctly except for the icons. but the relativeness of the paths might be decided on something else, and the fault then doesn't ly with Qt.py
```python
from Qt import _loadUi
_loadUi(UI_PATH, self)
```

**Comment by hannesdelbeke** [comment]
if i copy the icons folder to a higher folder, i can get it to work.
(1 folder above my project folder)
![image](https://github.com/leixingyu/unrealScriptEditor/assets/3758308/b949e2ba-9cb9-49d4-ac06-66d853d20f07)
![image](https://github.com/leixingyu/unrealScriptEditor/assets/3758308/4a9eca7c-788e-40b5-8a40-e2d44b2c483c)

**Comment by hannesdelbeke** [comment]
if in pycharm i change the working directory to the icons, codeeditor or ui folder, the relative paths start to work, and the icons show up.
so it appears the relativeness in the path is from the working directory, not the `.ui` file

that also explains why it doesn't work in Unreal. the working directory is neither of those folders in the unreal projects.

**Comment by leixingyu** [comment]
weird, the startup.py should already be adding the root of the tool to sys.path which is basically what you described as adding the tool as working directory right?
did you add the startup.py as the startup file for unreal at all, if so, can you print out the sys.path and paste it here?

**Comment by hannesdelbeke** [comment]
paths in the original code
```
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin',
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\venv',
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\venv\\lib\\site-packages',
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\PythonScriptEditor\\Content\\Python',
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\PythonScriptEditor\\Content\\Python\\unrealScriptEditor\\..',
 ```

 my working dir was set to the icons folder, so tried adding that to path but it doesn't fix the issue
 ```
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\PythonScriptEditor\\Content\\Python\\unrealScriptEditor\\icons',
 'C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\PythonScriptEditor\\Content\\Python\\unrealScriptEditor']
 ```
 
 i think working dir might be similar to active dir when you run commands.
 e.g. when you `cd` to a folder in the terminal.

**Comment by hannesdelbeke** [comment]
adding to the path didn't fix it
but when i add the following line, to change the working dir it works
 ```python
import os
os.chdir("C:\\Users\\user\\repos\\unrealScriptEditor-plugin\\PythonScriptEditor\\Content\\Python\\unrealScriptEditor\\icons")
```
![image](https://github.com/leixingyu/unrealScriptEditor/assets/3758308/4a9eca7c-788e-40b5-8a40-e2d44b2c483c)

Not sure if this is a recommended thing to do in unreal though
maybe we can change working dir, and change it back to the original afterwards?

**Comment by hannesdelbeke** [comment]
what also worked, and is perhaps a cleaner solution

in the `.ui` file, change `../icons/executeAll.png` to `ICONS:/executeAll.png`
then run this in the `startup.py` file, before loading the UI
```python
from PySide2.QtCore import QDir

MODULE_PATH = os.path.dirname(os.path.abspath(__file__))
ICONS_PATH = os.path.join(MODULE_PATH, 'icons')
QDir.addSearchPath("ICONS", ICONS_PATH)
```

**Comment by hannesdelbeke** [comment]
made a PR #4

**Comment by hannesdelbeke** [comment]
found another solution for this, even cleaner.
```python
# change 
QtCore.QResource.registerResource("icons.rcc")
# to 
QtCore.QResource.registerResource(str(MODULE_PATH / "icons.rcc") )
```

now the rcc loads correctly, and no changes are needed to any other file. one line fix.
will create a PR for this in the original stylesheet repo

**Comment by leixingyu** [comment]
can you help me understand what this part is doing? `str(MODULE_PATH / "icons.rcc")`

**Comment by hannesdelbeke** [comment]
explanation

old code
```python
QtCore.QResource.registerResource("icons.rcc") 
# this assumes this script runs from the same folder as icons.rcc
# or that icons.rcc is in the path.
# if however you import the stylesheet as a module, or anywhere not in the main path
# the icons can't be found in the search path. 
```

new code
```python
QtCore.QResource.registerResource(str(MODULE_PATH / "icons.rcc") )
# the new code sets the Resource path to an explicit path, using pathlib
str(MODULE_PATH / "icons.rcc") # is actually the same as 
"C:\Users\hanne\OneDrive\Documents\repos\unrealStylesheet\unreal_qt_stylesheet\icons.rcc"
```
_reference: see [pyside searchpath docs](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QIcon.html#PySide2.QtGui.PySide2.QtGui.QIcon.themeSearchPaths)_

This approach means only a single line of code change is needed to fix the path  
So we don't need these changes:
- the merged in approach [changed several files](https://github.com/leixingyu/unrealScriptEditor/pull/4/files) to fix it.
- you also [changed icon paths](https://github.com/leixingyu/unrealScriptEditor/commit/8666b4b319284eaf39c160829ab29e69bbbd283e) to fix the issue, which didnt fix it but was still merged in
- another [attempt to fix,](https://github.com/leixingyu/unrealScriptEditor/commit/4b24539d83078ab052c75faa830b191ee019d42d) by adding to sys path, ideally packages should avoid doing this since it changes import behaviour for other scripts.

**Comment by hannesdelbeke** [comment]
by the way, i don't think this needs changing in this repo, since we will fix this in the stylesheet repo,
and this issue is already fixed in this repo.
