### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by hannesdelbeke** [leixingyu/unrealScriptEditor#7]
hi,

- [x] i've released a version to PYPI https://pypi.org/project/unreal-script-editor/
- [x] create PR with PIP install isntructions https://github.com/leixingyu/unrealScriptEditor/pull/8
- [x] we already have a github workflow in the repo for automated release 
- [x] can you accept the invite for the PYPI project?
- [ ] can we set up a secret on this github repo for future releases?
- [ ] (optional step) to stay consistent with the PYPI project and PEP naming convention, we could rename the github repo to `unreal-script-editor` 
- [x] (optional step) if you want help with future updates in this repo you could make me a maintainer for the github repo.

**Comment by leixingyu** [comment]
I've setup the pypi part, what step should I follow to make you the maintainer?

**Comment by hannesdelbeke** [comment]
you can add people and choose their role, in the github settings of your project
![image](https://github.com/leixingyu/unrealScriptEditor/assets/3758308/1147c17b-41a4-4570-bb93-4a2257018c08)
